development:
  sessions:
    default:
      database: sentimention_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: sentimention_test
      hosts:
        - localhost:27017