development:
  sessions:
    default:
      database: sentimention_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: sentimention_test
      hosts:
        - localhost:27017
        
test:
  uri: mongodb://sentimention:sentimention@ds037467-a.mongolab.com:37467/heroku_app6775421